### PR TITLE
Add 'foldMaybe'

### PR DESCRIPTION
**Pull request by garyb**
I find myself writing something in this pattern very frequently (almost daily lately). I know we're all about the Fairbairn threshold, etc. but this one seems reasonable enough to me at least?

### CODE REVIEW

**Comment by garyb** [comment]
I guess it's just `foldl f a b` too, but 🤷‍♂️

**Comment by natefaubion** [comment]
I honestly would just like a flipped `foldl`, which I write often. I'm not sure why we would want it fixed to `Maybe`.

**Comment by LiamGoodacre** [comment]
`fancyFold = u # foldl \a x -> annoyingly long function`?

**Comment by garyb** [comment]
`foldl` is fine for my needs, it's just in the process of this that I realised that's what I always wanted :wink:

**Pull request closed without merging**
