### PR TITLE
Avoid exporting unsafeThrow from Data.Maybe.Unsafe

### PR DESCRIPTION
**Pull request by hdgarrood**

### CODE REVIEW

**Comment by paf31** [comment]
Breaking change, technically, but looks good, thanks.

**Comment by garyb** [comment]
Yeah, I have a feeling that this might be used elsewhere :disappointed: 

We'll be able to remove this anyway in 0.8 since they'll gain `Partial` constraints instead (I assume?)

**Comment by Thimoteus** [comment]
There's also `unsafeThrow` from purescript-exceptions. It's strange to see the same function in a Maybe library.

**Comment by hdgarrood** [comment]
It was an oversight (mine) that this was ever exported, yeah.

**Comment by hdgarrood** [comment]
close this in favour of #20?

**Comment by garyb** [comment]
:+1:

**Pull request closed without merging**
